sudo: required
services:
  - docker

before_install:
  - cd section-6_Production-workflow/frontend
  - docker build -t jvanryck/docker-react -f Dockerfile.dev .

script:
  - docker run jvanryck/docker-react npm run test -- --coverage
